### ISSUE TITLE
pkg-config integration

### ISSUE THREAD

**Issue by tpetazzoni** [mbats/eclipse-buildroot-bundle#1]
Integrate pkg-config plugin in the Bundle. The plug-in will need to be modified to adapt to the different PKG_CONFIG_PATH and PKG_CONFIG_SYSROOTDIR per Buildroot toolchain.

**Comment by mbats** [comment]
Patches integrated to  pkg-config support git repository : http://code.google.com/p/pkg-config-support-for-eclipse-cdt/source/
