### ISSUE TITLE
tutorial update :

### ISSUE THREAD

**Issue by boucman** [mbats/eclipse-buildroot-bundle#10]
the documentation at https://github.com/mbats/eclipse-buildroot-bundle/wiki/Tutorial-:-How-to-activate-and-install-the-Buildroot-Eclipse-plugin-%3F specifies that it is needed to patch buildroot to be able to register toolchains. 

the patch has been integrated in the recently released 2013.02 version of buildroot. 

it might be usefull to keep the patch around for people using older versions of buildroot, but the documentation is currently misleading...

**Comment by mbats** [comment]
I updated the tutorial. Thanks!
