### ISSUE TITLE
various small problems with documentation

### ISSUE THREAD

**Issue by boucman** [mbats/eclipse-buildroot-bundle#11]
while going through the tutorials I found a couple of problems

in the "how to install" tutorial
- there is a R2 release for juno, which works fine. You still point to R1
- the screenshot has 3 features, but when I actually did it there was only one. this is slightly confusing

in the "how to run" tutorial
- you say that the sftp server will be in the next release, it is now available

in the "remote debug" tutorial
- the option "gdb for the host" needs to be configured in buildroot, since it's the cross-gdb and not the native gdb that is used

overall this thing is awesome, thx a lot for the contribution

**Comment by tpetazzoni** [comment]
Thanks a lot for your feedback. We've fixed all those issues in the tutorials.
