### ISSUE TITLE
Does not work in Kepler

### ISSUE THREAD

**Issue by xhpohanka** [mbats/eclipse-buildroot-bundle#17]
Hi,
I have quickly tried this plugin with actual Eclipse Kepler and it does not work well. Installing this plugin causes Eclipse to think that there are no compatible toolchains for current platform and even after unchecking the compatibility checkbox Buildroot toolchain is not there.

**Comment by mbats** [comment]
Yes I have to provide a new version compatible with the new version of CDT available in Kepler. It would be released soon, I expect at the end of next week.

**Comment by xhpohanka** [comment]
Thanks for fast response, I'm looking forward new version...

**Comment by mbats** [comment]
The new version 3.0.0 is compatible with kepler. The update-site is available on http://buildroot.org/downloads/eclipse/kepler/.
