### ISSUE TITLE
Properly set the sysroot when debugging

### ISSUE THREAD

**Issue by tpetazzoni** [mbats/eclipse-buildroot-bundle#18]
Currently, the Buildroot Eclipse plugin sets the solib-search-path to tell the cross debugger where the cross-compiled libraries can be found on the host machine. However, this does not work properly as it does not allow the cross debugger to find the dynamic linker location on the host machine.

The proper way to fix this is to set the sysroot for the cross debugger. Since Eclipse does not have a place to set this configuration, a possible solution is to use a gdbinit file which contains the command "set sysroot /path/to/staging/directory".

**Comment by mbats** [comment]
Fixed in 3.2.0.
See : https://github.com/mbats/eclipse-buildroot-toolchain-plugin/commit/61acff911aa37ca80b422ec8e044264c1f02401b
