### ISSUE TITLE
Add support for archiver

### ISSUE THREAD

**Issue by tpetazzoni** [mbats/eclipse-buildroot-bundle#19]
The current Buildroot plugin does not register the Archiver tool, which causes Eclipse to use the C Linker to create static libraries. This fails because doing gcc -o foo.a foo.o cannot work, and obviously fails.

**Comment by mbats** [comment]
Fixed by https://github.com/mbats/eclipse-buildroot-toolchain-plugin/commit/683e1c508a3fe80b28996a26e92deee92f8ff3b1
