### ISSUE TITLE
Update for NEON

### ISSUE THREAD

**Issue by aduskett** [mbats/eclipse-buildroot-bundle#24]
Hi,

Eclipse NEON is incompatible with Luna plugins, and as such, the plugin
had to be patched to work properly with eclipse.  I dug through the code a bit
and modified it enough to work properly with NEON.2 (at least in my testing.)

I create a patch that I hope you guys could use.

Any imports that were changed were because of deprecated libraries that
were no longer used, available, or had changed.

[0001-Update-toolchain-to-work-with-Eclipse-NEON.2.txt](https://github.com/mbats/eclipse-buildroot-bundle/files/842724/0001-Update-toolchain-to-work-with-Eclipse-NEON.2.txt)

**Comment by niallp** [comment]
@aduskett Could you perhaps provide a few instructions on how to apply the patch ? As a mere Eclipse user I can't locate the files that are patched anywhere ... thanks !
