### ISSUE TITLE
Set a proper PATH by default

### ISSUE THREAD

**Issue by mbats** [mbats/eclipse-buildroot-bundle#7]
In order for the autotools plugin to behave properly, the $(O)/host/usr/bin directory must be in the PATH. The PATH must be set in the project properties -> C/C++ Build -> Environment.

It is also important that $(O)/host/usr/bin is prepended to the default system path, because tools provided by Buildroot (autoconf, autoreconf, pkg-config, etc.) must be used in preference to system tools.

**Comment by tpetazzoni** [comment]
Implemented in the 2.0.0 release.
